name: build

on:
  pull_request: &ignore-paths
    paths-ignore:
      - 'docs/**'
      - '.github/CONTRIBUTING.md'
      - '.github/FUNDING.yml'
      - '.github/SECURITY.md'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE.md'
      - 'UPGRADE.md'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'
      - 'docker-compose.yml'
      - 'Makefile'

  push: *ignore-paths

permissions:
  contents: read
jobs:
  phpunit:
    uses: yiisoft/yii2-actions/.github/workflows/phpunit.yml@master
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      extensions: pdo, pdo_sqlite
      php-version: '["8.1","8.2","8.3","8.4","8.5"]'
